name: Our first python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  My-first-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      #- name: Set up uv
      #  uses: astral-sh/setup-uv@v3
      #- name: Install the project dependencies using uv
      #  run: uv sync --locked --all-extras --dev
      - name: Lint with Ruff
        run: |
          run ruff check
      - name: Test with pytest
        run: run pytest tests
